openapi: 3.0.0
info:
  title: Ecotech HR API
  description: 'API untuk layanan HR internal, termasuk profil karyawan dan manajemen cuti.'
  version: 1.1.0
servers:
  - url: https://ecomate-e3b5cshbgcewfehz.canadacentral-01.azurewebsites.net
    description: Server Produksi di Azure
  - url: http://localhost:3000
    description: Server development lokal

paths:
  /login:
    get:
      summary: 1. Memulai Alur Login
      description: Mengalihkan pengguna ke halaman login Microsoft Azure AD untuk autentikasi.
      responses:
        '302':
          description: Berhasil dialihkan ke halaman login Microsoft.

  /auth/callback:
    get:
      summary: 2. Callback & Menampilkan OTP
      description: Menangani callback dari Azure AD. Jika sukses, menampilkan halaman HTML dengan 6-digit OTP yang berlaku 5 menit.
      responses:
        '200':
          description: Sukses. Menampilkan halaman HTML dengan kode OTP.
          content:
            text/html: {}
        '500':
          description: Gagal mendapatkan token dari Microsoft.

  /exchange-otp:
    post:
      summary: 3. Menukar OTP dengan API Key
      description: Endpoint untuk agent AI (Pusaka) menukarkan 6-digit OTP dengan API Key (JWT) jangka panjang.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  description: 6-digit OTP yang didapat dari halaman callback.
              required:
                - otp
              example:
                otp: "123456"
      responses:
        '200':
          description: Berhasil menukar OTP. Mengembalikan API Key.
          content:
            application/json:
              schema:
                type: object
                properties:
                  apiKey:
                    type: string
                    description: API Key (JWT) yang berlaku selama 90 hari.
        '400':
          description: OTP tidak disertakan dalam request body.
        '404':
          description: OTP tidak valid atau sudah kedaluwarsa.

  /whoami:
    get:
      summary: Get Current User Identity
      description: 'Mengambil informasi identitas user yang sedang login, baik via Cookie maupun API Key.'
      security:
        - cookieAuth: []
        - bearerAuth: []
      responses:
        '200':
          description: Data identitas berhasil diambil.
        '401':
          description: Tidak terautentikasi.

  /healthz:
    get:
      summary: Health Check
      description: Memeriksa status server.
      responses:
        '200':
          description: Server berjalan dengan baik.

  /profile/personal-info:
    get:
      summary: Get Own Profile
      description: 'Mengambil data personal lengkap milik user yang sedang login.'
      security:
        - cookieAuth: []
        - bearerAuth: []
      responses:
        '200':
          description: Data profil berhasil diambil.
        '401':
          description: 'Tidak terautentikasi (belum login).'
        '404':
          description: Data tidak ditemukan.

  /admin/profile/search:
    get:
      summary: 'Admin: Search and Get Employee Profile'
      description: '(Admin) Mengambil data personal lengkap karyawan berdasarkan kriteria.'
      security:
        - cookieAuth: []
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          schema:
            type: string
          description: 'GUID dari karyawan.'
        - name: code
          in: query
          schema:
            type: string
          description: 'Employee Code (e.g., ES-0022).'
        - name: email
          in: query
          schema:
            type: string
          description: 'Email karyawan.'
        - name: name
          in: query
          schema:
            type: string
          description: 'Nama karyawan.'
      responses:
        '200':
          description: Daftar profil karyawan berhasil diambil.
        '403':
          description: 'Akses ditolak (bukan admin).'

  /profile/{employeeId}:
    patch:
      summary: 'Update Profile (Admin)'
      description: '(Admin) Memperbarui data personal seorang karyawan.'
      security:
        - cookieAuth: []
        - bearerAuth: []
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: 'GUID dari karyawan yang ingin diubah.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              # ... (properti lainnya sama seperti sebelumnya)
      responses:
        '200':
          description: Profil berhasil diperbarui.
        '403':
          description: 'Akses ditolak (bukan admin).'

  /leave-preview:
    post:
      summary: Leave Preview
      description: 'Menghitung tanggal selesai cuti berdasarkan tanggal mulai dan jumlah hari.'
      security:
        - cookieAuth: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                start_date:
                  type: string
                  format: date
                days:
                  type: integer
      responses:
        '200':
          description: Preview berhasil dihitung.

  # ... (semua endpoint Cuti lainnya juga perlu ditambahkan security) ...
  /leave/types:
    get:
      summary: Get All Leave Types
      security:
        - cookieAuth: []
        - bearerAuth: []
      # ... (sisa definisi sama)

  /leave/balance:
    get:
      summary: Get Saldo Cuti User
      security:
        - cookieAuth: []
        - bearerAuth: []
      parameters:
        - name: period
          in: query
          required: true
          schema:
            type: string
          description: 'Periode tahun yang ingin diperiksa (contoh: 2023).'
      responses:
        '200':
          description: Saldo cuti berhasil diambil.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    leave_type_id:
                      type: string
                    leave_type_name:
                      type: string
                    quota:
                      type: integer
                    balance:
                      type: integer
                    end_date:
                      type: string
                      format: date-time

  /leave/requests:
    get:
      summary: "Get User's Leave Requests"
      security:
        - cookieAuth: []
        - bearerAuth: []
      # ... (sisa definisi sama)
    post:
      summary: Apply for Leave
      security:
        - cookieAuth: []
        - bearerAuth: []
      # ... (sisa definisi sama)

  /leave/requests/{leaveId}/cancel:
    post:
      summary: Cancel a Leave Request
      security:
        - cookieAuth: []
        - bearerAuth: []
      # ... (sisa definisi sama)

  /admin/leave-requests:
    get:
      summary: 'Admin: List all leave requests'
      security:
        - cookieAuth: []
        - bearerAuth: []
      # ... (sisa definisi sama)

  /admin/leave-requests/search:
    get:
      summary: "Admin: Search for employee's leave requests"
      security:
        - cookieAuth: []
        - bearerAuth: []
      parameters:
        - name: employeeId
          in: query
          schema:
            type: string
          description: 'GUID dari karyawan.'
        - name: email
          in: query
          schema:
            type: string
          description: 'Email karyawan.'
        - name: name
          in: query
          schema:
            type: string
          description: 'Nama karyawan.'
      responses:
        '200':
          description: Daftar permintaan cuti karyawan berhasil diambil.
        '403':
          description: 'Akses ditolak (bukan admin).'

  /admin/leave-balance/search:
    get:
      summary: "Admin: Search for employee's leave balance"
      security:
        - cookieAuth: []
        - bearerAuth: []
      parameters:
        - name: period
          in: query
          required: true
          schema:
            type: string
          description: 'Periode tahun yang ingin diperiksa (contoh: 2023).'
        - name: employeeId
          in: query
          schema:
            type: string
          description: 'GUID dari karyawan.'
        - name: email
          in: query
          schema:
            type: string
          description: 'Email karyawan.'
        - name: name
          in: query
          schema:
            type: string
          description: 'Nama karyawan.'
      responses:
        '200':
          description: Daftar saldo cuti karyawan berhasil diambil.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    leave_type_id:
                      type: string
                    leave_type_name:
                      type: string
                    quota:
                      type: integer
                    balance:
                      type: integer
                    end_date:
                      type: string
                      format: date-time
        '403':
          description: 'Akses ditolak (bukan admin).'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
      description: Autentikasi berbasis sesi cookie untuk interaksi via browser.
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Autentikasi berbasis Bearer Token (API Key) untuk agent AI atau sistem eksternal.