openapi: 3.0.3
info:
  title: HRIS API
  version: 1.0.0
  description: HRIS OpenAPI Specification

servers:
  - url: https://ecomate-phi.vercel.app
    description: Server Produksi di Vercel

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /login:
    get:
      tags:
        - Auth
      summary: Login via Azure AD
      description: Redirect user to Azure AD login page
      responses:
        '302':
          description: Redirect to Azure AD

  /auth/callback:
    get:
      tags:
        - Auth
      summary: Azure OAuth callback
      description: Handle Azure AD OAuth callback and generate OTP
      responses:
        '200':
          description: OTP generated

  /show-otp:
    get:
      tags:
        - Auth
      summary: Show OTP (development only)
      responses:
        '200':
          description: OTP visible

  /exchange-otp:
    post:
      tags:
        - Auth
      summary: Exchange OTP for JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
              properties:
                otp:
                  type: string
                  description: One-time password
      responses:
        '200':
          description: JWT issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: integer
                    example: 86400
        '400':
          description: Invalid or expired OTP

  /app-token:
    get:
      tags:
        - Auth
      summary: Get application JWT token
      responses:
        '200':
          description: App token issued

  /whoami:
    get:
      tags:
        - Auth
      summary: Get current authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Current user info

  /profile/personal-info:
    get:
      tags:
        - Profile
      summary: Get own personal information
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Personal info returned

  /profile/position:
    get:
      tags:
        - Profile
      summary: Get own current position and grade
      description: Retrieves the most recent active position and grade for the logged-in user.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Current active position and grade.
        '404':
          description: No active position record found.

  /admin/position/search:
    get:
      tags:
        - Admin
      summary: Search for an employee's position history
      description: Retrieves the entire position and grade history for a specific employee.
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: employeeId
          schema:
            type: string
          description: 'Search by the employee''s personal information GUID.'
        - in: query
          name: email
          schema:
            type: string
          description: 'Search by the employee''s work email address.'
        - in: query
          name: name
          schema:
            type: string
          description: 'Search by the employee''s name.'
      responses:
        '200':
          description: A list of historical position records for the employee.
        '400':
          description: One of the search parameters must be provided.
        '404':
          description: Employee not found.

  /leave/types:
    get:
      tags:
        - Leave
      summary: List leave types
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Leave types list

  /leave/requests:
    get:
      tags:
        - Leave
      summary: Get own leave requests
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Leave requests list

  /leave/requests/special:
    post:
      tags:
        - Leave
      summary: Apply for special leave
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - leave_typeid
                - start_date
                - days
              properties:
                leave_typeid:
                  type: string
                start_date:
                  type: string
                  format: date
                days:
                  type: integer
                reason:
                  type: string
      responses:
        '201':
          description: Leave created
        '400':
          description: Validation error

  /leave/requests/{leaveId}/cancel:
    post:
      tags:
        - Leave
      summary: Cancel leave request
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: leaveId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Leave cancelled

  /admin/leave-requests:
    get:
      tags:
        - Admin
      summary: List or search leave requests
      description: >
        Retrieves a list of leave requests. Can be used to list all requests within a date range,
        or to search for requests for a specific employee.
        If no parameters are provided, it will return all leave requests.
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: date
          description: 'Filter by start date of the leave period (e.g., YYYY-MM-DD). Use with endDate.'
        - in: query
          name: endDate
          schema:
            type: string
            format: date
          description: 'Filter by end date of the leave period (e.g., YYYY-MM-DD). Use with startDate.'
        - in: query
          name: month
          schema:
            type: string
          description: 'Filter by a specific month (e.g., "2026-01"). Overrides startDate and endDate.'
        - in: query
          name: year
          schema:
            type: string
          description: 'Filter by a specific year (e.g., "2026"). Used if month is not provided.'
        - in: query
          name: employeeId
          schema:
            type: string
          description: 'Filter by the employee''s personal information GUID.'
        - in: query
          name: email
          schema:
            type: string
          description: 'Filter by the employee''s work email address.'
        - in: query
          name: name
          schema:
            type: string
          description: 'Filter by the employee''s name.'
        - in: query
          name: for
          schema:
            type: string
            enum: [ai]
          description: 'Set to "ai" to receive a summarized, token-friendly response suitable for AI agents.'
      responses:
        '200':
          description: A list of leave requests.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ecom_leaverequestid:
                      type: string
                      description: Primary identifier for the leave request (UUID)
                    ecom_name:
                      type: string
                    ecom_startdate:
                      type: string
                      format: date
                    ecom_enddate:
                      type: string
                      format: date
                    ecom_numberofdays:
                      type: number
                    ecom_leavestatus:
                      type: integer
        '403':
          description: Admin access required.

  /leave/history:
    get:
      tags:
        - Leave
      summary: Get own leave history
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Leave history          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ecom_leaverequestid:
                      type: string
                      description: Primary identifier for the leave request (UUID)
                    ecom_name:
                      type: string
                    ecom_startdate:
                      type: string
                      format: date
                    ecom_enddate:
                      type: string
                      format: date
                    ecom_numberofdays:
                      type: number
                    ecom_leavestatus:
                      type: integer
  /admin/leave-history/search:
    get:
      tags:
        - Admin
      summary: Search leave history
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Leave history result

  /developments:
    get:
      tags:
        - Development
      summary: Get own development history
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Development history

  /admin/developments/search:
    get:
      tags:
        - Admin
      summary: Search development history
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Development history result

  /summary-peer-review:
    get:
      tags:
        - Review
      summary: Get own summary peer review
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Peer review summary

  /admin/summary-peer-review/search:
    get:
      tags:
        - Admin
      summary: Search summary peer review
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Peer review search result